"""
BRIDGE GUARD V2
===============

Independent behavioral verification between:

    LEGACY COBOL
          ↓
    known behavior
          ↓
    modern Python generated by Bob

This version performs a SMALL, focused verification suite.

It is intentionally not exhaustive.
The objective is to detect the most important behavioral
divergences before accepting the modernization.
"""

from decimal import Decimal
from pathlib import Path
import importlib.util
import sys


# ============================================================
# PATHS
# ============================================================

ROOT = Path(__file__).resolve().parent

MODERN_FILE = (
    ROOT.parent
    / "04_modernization"
    / "modern_payment_processor.py"
)

# ============================================================
# LOAD MODERN IMPLEMENTATION
# ============================================================

def load_modern_module():
    """Load Bob's generated Python implementation."""

    if not MODERN_FILE.exists():
        raise FileNotFoundError(
            f"Modern implementation not found:\n{MODERN_FILE}"
        )

    spec = importlib.util.spec_from_file_location(
        "modern_payment_processor",
        MODERN_FILE
    )

    if spec is None or spec.loader is None:
        raise ImportError(
            "Could not load modern_payment_processor.py"
        )

    module = importlib.util.module_from_spec(spec)

    # Required for dynamically loaded dataclass modules.
    sys.modules[spec.name] = module

    spec.loader.exec_module(module)

    return module


# ============================================================
# LEGACY BEHAVIOR
# ============================================================

def legacy_expected_status(
    amount: Decimal,
    credit_limit: Decimal
) -> str:
    """
    Independent representation of the COBOL rule.

    COBOL:

        IF HV-AMOUNT <= HV-CREDIT-LIMIT
            APPROVED
        ELSE
            REVIEW
    """

    if amount <= credit_limit:
        return "APPROVED"

    return "REVIEW"


# ============================================================
# TEST 1 — BELOW LIMIT
# ============================================================

def test_below_limit(modern):
    """
    499.99 <= 500.00
    Expected: APPROVED
    """

    return verify_status(
        modern,
        "499.99",
        "500.00",
        "Below credit limit"
    )


# ============================================================
# TEST 2 — EXACT BOUNDARY
# ============================================================

def test_equal_limit(modern):
    """
    500.00 <= 500.00
    Expected: APPROVED

    This is the critical COBOL boundary.
    """

    return verify_status(
        modern,
        "500.00",
        "500.00",
        "Exact credit-limit boundary"
    )


# ============================================================
# TEST 3 — ABOVE LIMIT
# ============================================================

def test_above_limit(modern):
    """
    500.01 > 500.00
    Expected: REVIEW
    """

    return verify_status(
        modern,
        "500.01",
        "500.00",
        "Above credit limit"
    )


# ============================================================
# TEST 4 — ZERO AMOUNT
# ============================================================

def test_zero_amount(modern):
    """
    0.00 <= 500.00
    Expected: APPROVED
    """

    return verify_status(
        modern,
        "0.00",
        "500.00",
        "Zero amount"
    )


# ============================================================
# TEST 5 — DECIMAL TYPE
# ============================================================

def test_decimal_representation(modern):
    """
    Monetary values must use Decimal rather than float.
    """

    record = modern.PaymentRecord(
        payment_id=1,
        account_id=100,
        amount=Decimal("500.00"),
        credit_limit=Decimal("500.00"),
        status="PENDING",
        customer_name="BRIDGE GUARD TEST"
    )

    passed = (
        isinstance(record.amount, Decimal)
        and isinstance(record.credit_limit, Decimal)
    )

    print(
        f"{'Decimal monetary representation':<40} | "
        f"{'PASS' if passed else 'MISMATCH'}"
    )

    return passed


# ============================================================
# TEST 6 — ACCOUNT_ID PRESERVED
# ============================================================

def test_account_id_present(modern):
    """
    ACCOUNT_ID must exist in the modern data model.

    It is carried through the model but is not used
    in the business decision.
    """

    record = modern.PaymentRecord(
        payment_id=1,
        account_id=12345,
        amount=Decimal("100.00"),
        credit_limit=Decimal("500.00"),
        status="PENDING",
        customer_name="BRIDGE GUARD TEST"
    )

    passed = (
        hasattr(record, "account_id")
        and record.account_id == 12345
    )

    print(
        f"{'ACCOUNT_ID preserved in model':<40} | "
        f"{'PASS' if passed else 'MISMATCH'}"
    )

    return passed


# ============================================================
# TEST 7 — STATUS PRESENT
# ============================================================

def test_status_present(modern):
    """
    STATUS must remain present in the data model.
    """

    record = modern.PaymentRecord(
        payment_id=1,
        account_id=100,
        amount=Decimal("100.00"),
        credit_limit=Decimal("500.00"),
        status="PENDING",
        customer_name="BRIDGE GUARD TEST"
    )

    passed = (
        hasattr(record, "status")
        and record.status == "PENDING"
    )

    print(
        f"{'STATUS preserved in model':<40} | "
        f"{'PASS' if passed else 'MISMATCH'}"
    )

    return passed


# ============================================================
# TEST 8 — OPERATOR VERIFICATION
# ============================================================

def test_operator_is_lte(modern):
    """
    Explicitly verify the critical <= boundary.

    This prevents an accidental modernization from changing:

        <=

    into:

        <
    """

    equal_result = verify_status(
        modern,
        "250.00",
        "250.00",
        "Operator <= boundary"
    )

    return equal_result


# ============================================================
# STATUS VERIFICATION HELPER
# ============================================================

def verify_status(
    modern,
    amount_text: str,
    limit_text: str,
    description: str
) -> bool:

    amount = Decimal(amount_text)
    limit = Decimal(limit_text)

    # Independent COBOL expectation.
    expected = legacy_expected_status(
        amount,
        limit
    )

    # Build modern record.
    record = modern.PaymentRecord(
        payment_id=1,
        account_id=100,
        amount=amount,
        credit_limit=limit,
        status="PENDING",
        customer_name="BRIDGE GUARD TEST"
    )

    # Execute modern business logic.
    actual = modern.evaluate_payment(
        record.amount,
        record.credit_limit
    )

    passed = expected == actual

    print(
        f"{description:<40} | "
        f"LEGACY={expected:<8} | "
        f"MODERN={actual:<8} | "
        f"{'PASS' if passed else 'MISMATCH'}"
    )

    return passed


# ============================================================
# MAIN
# ============================================================

def main():

    print()
    print("=" * 72)
    print("BRIDGE GUARD V2")
    print("Legacy → Modern Behavioral Verification")
    print("=" * 72)
    print()

    # --------------------------------------------------------
    # LOAD
    # --------------------------------------------------------

    print("[1] Loading modern implementation...")

    try:
        modern = load_modern_module()
    except Exception as exc:
        print()
        print("ERROR loading modern implementation:")
        print(exc)
        return 1

    print("    OK")

    # --------------------------------------------------------
    # INTERFACE
    # --------------------------------------------------------

    print()
    print("[2] Checking generated implementation...")

    required = [
        "PaymentRecord",
        "evaluate_payment",
    ]

    for name in required:

        if not hasattr(modern, name):

            print()
            print(
                f"ERROR: generated module does not expose "
                f"'{name}'."
            )

            return 1

    print("    OK")

    # --------------------------------------------------------
    # TESTS
    # --------------------------------------------------------

    print()
    print("[3] Focused behavioral verification")
    print("-" * 72)

    tests = [
        ("BR-02", test_below_limit),
        ("BR-02", test_equal_limit),
        ("BR-03", test_above_limit),
        ("BR-02", test_zero_amount),
        ("DATA", test_decimal_representation),
        ("DATA", test_account_id_present),
        ("DATA", test_status_present),
        ("BR-02", test_operator_is_lte),
    ]

    results = []

    for rule_id, test_function in tests:

        try:
            result = test_function(modern)
        except Exception as exc:

            print(
                f"{rule_id:<7} | "
                f"{test_function.__name__:<35} | "
                f"ERROR: {exc}"
            )

            result = False

        results.append(result)

    # --------------------------------------------------------
    # SUMMARY
    # --------------------------------------------------------

    passed = sum(results)
    total = len(results)

    print()
    print("=" * 72)

    if passed == total:

        print(
            f"RESULT: VERIFIED "
            f"({passed}/{total} focused checks passed)"
        )

        print()
        print(
            "The modern implementation preserves the "
            "tested legacy behavior."
        )

        print()
        print(
            "IMPORTANT: This is focused verification, "
            "not exhaustive equivalence testing."
        )

        print("=" * 72)

        return 0

    print(
        f"RESULT: BLOCKED "
        f"({passed}/{total} checks passed)"
    )

    print()
    print(
        "Behavioral mismatch detected."
    )

    print(
        "The modernization must NOT be accepted."
    )

    print("=" * 72)

    return 1


# ============================================================
# ENTRY POINT
# ============================================================

if __name__ == "__main__":
    sys.exit(main())